### ISSUE TITLE
页脚的设置貌似有问题吧？

### ISSUE THREAD

**Issue by BeanWei** [Sweet-KK/css-layout#2]
margin： 0 auto； 这样设置的页脚会跟着页面内容走，当页面内容很少的时候页脚不会在底部了。。。。

**Comment by Sweet-KK** [comment]
css的实现有太多了,其实不能一味的死搬,因为每个方法肯定有它的局限，只要能满足当前情况就ok了，如果出现你说的这种，那就考虑考虑别的实现方法或者再添加点样式做个兼容处理。无他，重要的是理解css，才能更好地使用它

**Comment by Sweet-KK** [comment]
css的实现有太多了,其实不能一味的死搬,因为每个方法肯定有它的局限，只要能满足当前情况就ok了，如果出现你说的这种，那就考虑考虑别的实现方法或者再添加点样式做个兼容处理。无他，重要的是理解css，才能更好地使用它
